### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Balogunolalere** [kadirnar/yolov9-pip#4]
![image](https://github.com/kadirnar/yolov9-pip/assets/38155412/726454f3-7788-4671-8019-29cceb08a429)

**Comment by kadirnar** [comment]
Can you check the path of the model file?

**Comment by Balogunolalere** [comment]
i am running on colab, cant see the model file

**Comment by kadirnar** [comment]
You should download it from here.

https://github.com/WongKinYiu/yolov9/releases
