### ISSUE TITLE
yolov9-c.pt not found

### ISSUE THREAD

**Issue by LordFarquaadtheCreator** [kadirnar/yolov9-pip#5]
Hello,
I was trying to use your pip installation to fine-tune the v9 model, however it threw an error saying first that `requirements.txt` was not found, as well as `yolov9-c.pt` not found.

How can I fix this? Or is this an issue with the package?

**Comment by kadirnar** [comment]
https://github.com/kadirnar/yolov9-pip/issues/4#issuecomment-1961582903
