### ISSUE TITLE
How to train pretrained model with customized dta? How to use own trained model for real time camera?

### ISSUE THREAD

**Issue by shoukewei** [kadirnar/yolov9-pip#6]
It is a great package. But how to train a pretrained model with customized data? and how to use own trained model for real real-time camera? Thank you.

**Comment by kadirnar** [comment]
This repo only supports inference. I will add it later.

**Comment by ajinkya-kulkarni** [comment]
Hi, any chance the training code will be added?

**Comment by kadirnar** [comment]
> Hi, any chance the training code will be added?

I stopped development because the ultralicts library released inference and training code for all yolo models.

https://docs.ultralytics.com/modes/train/
